title: Christian Cervellera
url: "https://christiancervellera.github.io"
baseurl: "/"

markdown: kramdown
ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "G. Salvemini: <<Noi non possiamo essere imparziali. Possiamo essere soltanto intellettualmente onesti: cioè renderci conto delle nostre passioni, tenerci in guardia contro di esse e mettere in guardia i nostri lettori contro i pericoli della nostra parzialità. L'imparzialità è un sogno, la probità è un dovere." 
>>"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "CV"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
